name: base
channels:
  - conda-forge
  - defaults
dependencies:
  - matplotlib
  - matplotlib-base
  - nbconvert
  - nbformat
  - numpy
  - numpy-base
  - pandas
  - pandoc
  - pandocfilters
  - paramiko
  - pip
  - scipy
  - sphinx
